# Generated by Django 2.2.2 on 2019-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=30)),
                ('team2', models.CharField(max_length=30)),
                ('toss_winner', models.CharField(max_length=30, null=True)),
                ('toss_decision', models.CharField(max_length=1, null=True)),
                ('result', models.CharField(max_length=10)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(max_length=30, null=True)),
                ('win_by_runs', models.IntegerField(null=True)),
                ('win_by_wickets', models.IntegerField(null=True)),
                ('player_of_match', models.CharField(max_length=30, null=True)),
                ('venue', models.CharField(max_length=50)),
                ('umpire1', models.CharField(max_length=30)),
                ('umpire2', models.CharField(max_length=30)),
                ('umpire3', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
