# Generated by Django 2.2.2 on 2019-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
